### ISSUE TITLE
how to get here - CH alignment

### ISSUE THREAD

**Issue by ClauLung** [newdesigncongress/wma-hk-web#75]
the circled phrased should be shown in a horizontal line,  this should relate to responsiveness of the web
![image](https://user-images.githubusercontent.com/95728978/227085649-91f11407-b859-4cfa-a3e1-58e02fbd4fc5.png)

**Comment by shibacomputer** [comment]
Fixed!

**Comment by ClauLung** [comment]
We cannot find the place in CMS to edit the paragraph now, and right now, we are showing EN in CH page ,  could we unhide and show in CMS for further editing? 
![Screenshot 2023-09-06 at 9 58 16 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/672630bd-669f-40b7-845e-a40a86301f29)

**Comment by lightlii** [comment]
This was a permissions issue, can you confirm you now see this in the CMS @ClauLung ? 
![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/9c586671-b419-4dd6-8076-fbbf5475ef1a)

**Comment by ClauLung** [comment]
yes I can edit this, but cannot edit these texts on this page 
but for these text, 
![Screenshot 2023-09-19 at 11 44 42 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/2a2f1012-66d4-4946-9f27-ff5a3d7766e4)
![Screenshot 2023-09-19 at 11 45 09 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/d7853750-146e-46e9-9079-23aa19e0b7fc)

it's not on this page 

and ENG is not showing the same as CH for the followings 
1) missing the "*" remarks on saturday and sunday 
2) "Closed" on monday is not shown in CH but we did enter in global translation in CMS

**Comment by lightlii** [comment]
> 1. * missing the "*" remarks on saturday and sunday

Fixed!

>  2. "Closed" on monday is not shown in CH but we did enter in global translation in CMS

Also fixed. This was broken because the key had been modified in the chinese entry... They always need to be identical (case-sensitive)

![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/9dc78271-0c30-441c-8262-a3d02aab2265)

![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/50e548f1-5156-4166-860d-911ba45c8d07)

Not sure how that happened because I'd previously restricted edit permissions on the key field. There's no reason to ever edit them and to add a new translation would always require code changes

I've removed it completely from view now so we should avoid that happening again:
![image](https://github.com/newdesigncongress/wma-hk-web/assets/32508751/39f25a8a-28fc-414c-b2a9-60a104061e63)

**Comment by ClauLung** [comment]
it's a good idea to restrict edit permissions on the key field , but still seeing it on my end, would we need to do any changes on this? 
![Screenshot 2023-09-27 at 8 51 54 AM](https://github.com/newdesigncongress/wma-hk-web/assets/95728978/45517109-e0c8-40bb-a6d7-17b728bc310b)

**Comment by lightlii** [comment]
> it's a good idea to restrict edit permissions on the key field , but still seeing it on my end, would we need to do any changes on this?

no
